# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - SavoryApp/*
      - SavorySpringAPI/*

pool:
  vmImage: ubuntu-latest
  
stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    
    - task: Maven@3
      inputs:
        mavenPomFile: '$(System.DefaultWorkingDirectory)/SavorySpringAPI/pom.xml'
        goals: 'clean package'
        options: '-Dmaven.test.skip'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - script: |
        npm install
      displayName: 'npm install'
      workingDirectory: '$(System.DefaultWorkingDirectory)/SavoryApp'
      
    - script: |
        npm run build
      displayName: 'npm run build'
      workingDirectory: '$(System.DefaultWorkingDirectory)/SavoryApp'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/SavoryApp/build'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish JAR'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/SavorySpringAPI/.mvn/wrapper/maven-wrapper.jar'
        ArtifactName: 'jarArtifact'
        
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs: 
  - deployment: DeployJob
    displayName: 'Deployment Job'
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'jarArtifact'
                downloadPath: '$(Build.ArtifactStagingDirectory)'
            
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(Build.ArtifactStagingDirectory)'

            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'SavoryServiceConnection'
                appType: 'webApp'
                WebAppName: 'Savory'
                packageForLinux: '$(Build.ArtifactStagingDirectory)/drop'
            
            # Copy files to wwwroot directory using FTP
            # - task: FtpUpload@2
            #   displayName: 'FTP Upload'
            #   inputs:
            #     credentialsOption: 'inputs'
            #     serverUrl: 'ftps://waws-prod-blu-511.ftp.azurewebsites.windows.net/site/wwwroot'
            #     username: 'Savory\$Savory'
            #     password: 'AQLq02zRsqNvQoZJRad4bVFlAyWjsgE.m3Cb5i5covTRiQEtPsM-RdE3v-z8b6XKIPv-f6nQWXA'
            #     rootDirectory: '$(Build.ArtifactStagingDirectory)/drop'
            #     remoteDirectory: 'site/wwwroot'
            
            # # Additional step to deploy the frontend React application
            # - task: AzureRmWebAppDeployment@4
            #   inputs:
            #     ConnectionType: 'AzureRM'
            #     azureSubscription: 'SavoryServiceConnection'
            #     appType: 'webAppLinux'
            #     WebAppName: 'Savory'
            #     packageForLinux: '$(Build.ArtifactStagingDirectory)/drop'

