# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - SavoryApp/*
      - SavorySpringAPI/*

pool:
  vmImage: windows-latest
  
stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
  
    # - task: JavaToolInstaller@0
    #   inputs:
    #     versionSpec: '21'
    #     jdkArchitectureOption: 'x64'
    #     jdkSourceOption: PreInstalled
    
    - task: Maven@4
      inputs:
        mavenPomFile: '$(System.DefaultWorkingDirectory)/SavorySpringAPI/pom.xml'
        goals: 'clean compile package'
        options: '-Dmaven.test.skip'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    
    # - script: |
    #     java -jar savoryAPI-0.0.1-SNAPSHOT.jar
    #   displayName: 'Run SB App'
    #   workingDirectory: '$(System.DefaultWorkingDirectory)/SavorySpringAPI/target'

    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish JAR'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/SavorySpringAPI/target/savoryAPI-0.0.1-SNAPSHOT.jar'
        ArtifactName: 'jarArtifact'

    - script: |
        npm install
      displayName: 'npm install'
      workingDirectory: '$(System.DefaultWorkingDirectory)/SavoryApp'
      
    - script: |
        npm run build
      displayName: 'npm run build'
      workingDirectory: '$(System.DefaultWorkingDirectory)/SavoryApp'
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/SavoryApp/build'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        

    ## Publish the zip file
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        
